// Generated by `npm run gen-types` (@neondatabase/neon-js gen-types).
// DO NOT EDIT BY HAND — regenerate after every migration in src/db/migrations.
//
// Covers tables, views and functions in the public schema. Passed to
// NeonPostgrestClient<Database> in src/lib/data-api.ts, which is what makes
// every .from()/.rpc() call in the app type-checked.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      bill_charges: {
        Row: {
          amount: number
          bill_id: string
          id: string
          label: string
          owner_id: string
          sort_order: number
        }
        Insert: {
          amount?: number
          bill_id: string
          id?: string
          label: string
          owner_id?: string
          sort_order?: number
        }
        Update: {
          amount?: number
          bill_id?: string
          id?: string
          label?: string
          owner_id?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: "bill_charges_bill_fk"
            columns: ["bill_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "bills"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "bill_charges_bill_fk"
            columns: ["bill_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_bill_receipt"
            referencedColumns: ["id", "owner_id"]
          },
        ]
      }
      bills: {
        Row: {
          amount_paid: number
          bill_month: string
          created_at: string
          current_reading: number
          electricity_amount: number | null
          electricity_rate: number
          extra_charges_total: number
          id: string
          notes: string | null
          owner_id: string
          paid_on: string | null
          payment_method: string | null
          previous_balance: number
          previous_reading: number
          rent_amount: number
          tenant_id: string
          total_billed: number | null
          units_consumed: number | null
          updated_at: string
        }
        Insert: {
          amount_paid?: number
          bill_month: string
          created_at?: string
          current_reading?: number
          electricity_amount?: number | null
          electricity_rate?: number
          extra_charges_total?: number
          id?: string
          notes?: string | null
          owner_id?: string
          paid_on?: string | null
          payment_method?: string | null
          previous_balance?: number
          previous_reading?: number
          rent_amount?: number
          tenant_id: string
          total_billed?: number | null
          units_consumed?: number | null
          updated_at?: string
        }
        Update: {
          amount_paid?: number
          bill_month?: string
          created_at?: string
          current_reading?: number
          electricity_amount?: number | null
          electricity_rate?: number
          extra_charges_total?: number
          id?: string
          notes?: string | null
          owner_id?: string
          paid_on?: string | null
          payment_method?: string | null
          previous_balance?: number
          previous_reading?: number
          rent_amount?: number
          tenant_id?: string
          total_billed?: number | null
          units_consumed?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bills_tenant_fk"
            columns: ["tenant_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "bills_tenant_fk"
            columns: ["tenant_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_tenant_list"
            referencedColumns: ["id", "owner_id"]
          },
        ]
      }
      charge_presets: {
        Row: {
          amount: number
          house_id: string
          id: string
          label: string
          owner_id: string
        }
        Insert: {
          amount?: number
          house_id: string
          id?: string
          label: string
          owner_id?: string
        }
        Update: {
          amount?: number
          house_id?: string
          id?: string
          label?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "charge_presets_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "charge_presets_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_list"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "charge_presets_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_month_summary"
            referencedColumns: ["house_id", "owner_id"]
          },
        ]
      }
      houses: {
        Row: {
          address: string | null
          created_at: string
          deleted_at: string | null
          gpay_number: string | null
          id: string
          name: string
          number_of_floors: number
          owner_id: string
          updated_at: string
          upi_id: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string
          deleted_at?: string | null
          gpay_number?: string | null
          id?: string
          name: string
          number_of_floors?: number
          owner_id?: string
          updated_at?: string
          upi_id?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string
          deleted_at?: string | null
          gpay_number?: string | null
          id?: string
          name?: string
          number_of_floors?: number
          owner_id?: string
          updated_at?: string
          upi_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "v_owner_summary"
            referencedColumns: ["owner_id"]
          },
        ]
      }
      tenants: {
        Row: {
          aadhaar_number: string | null
          agreement_expiry: string | null
          created_at: string
          deleted_at: string | null
          electricity_rate: number
          floor_number: number
          house_id: string
          id: string
          is_active: boolean
          mobile_number: string | null
          monthly_rent: number
          moved_in_on: string
          moved_out_on: string | null
          name: string
          notes: string | null
          opening_meter_reading: number
          owner_id: string
          updated_at: string
        }
        Insert: {
          aadhaar_number?: string | null
          agreement_expiry?: string | null
          created_at?: string
          deleted_at?: string | null
          electricity_rate?: number
          floor_number: number
          house_id: string
          id?: string
          is_active?: boolean
          mobile_number?: string | null
          monthly_rent?: number
          moved_in_on?: string
          moved_out_on?: string | null
          name: string
          notes?: string | null
          opening_meter_reading?: number
          owner_id?: string
          updated_at?: string
        }
        Update: {
          aadhaar_number?: string | null
          agreement_expiry?: string | null
          created_at?: string
          deleted_at?: string | null
          electricity_rate?: number
          floor_number?: number
          house_id?: string
          id?: string
          is_active?: boolean
          mobile_number?: string | null
          monthly_rent?: number
          moved_in_on?: string
          moved_out_on?: string | null
          name?: string
          notes?: string | null
          opening_meter_reading?: number
          owner_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_list"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_month_summary"
            referencedColumns: ["house_id", "owner_id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          currency: string
          default_gpay_number: string | null
          default_upi_id: string | null
          id: string
          mobile_number: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          currency?: string
          default_gpay_number?: string | null
          default_upi_id?: string | null
          id?: string
          mobile_number?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          currency?: string
          default_gpay_number?: string | null
          default_upi_id?: string | null
          id?: string
          mobile_number?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      v_bill_receipt: {
        Row: {
          amount_paid: number | null
          balance_due: number | null
          bill_month: string | null
          electricity_amount: number | null
          electricity_rate: number | null
          extra_charges_total: number | null
          floor_number: number | null
          gpay_number: string | null
          house_id: string | null
          house_name: string | null
          id: string | null
          owner_id: string | null
          paid_on: string | null
          payment_method: string | null
          previous_balance: number | null
          rent_amount: number | null
          status: string | null
          tenant_id: string | null
          tenant_name: string | null
          total_billed: number | null
          units_consumed: number | null
          upi_id: string | null
        }
        Relationships: []
      }
      v_house_list: {
        Row: {
          address: string | null
          gpay_number: string | null
          id: string | null
          name: string | null
          number_of_floors: number | null
          owner_id: string | null
          tenant_count: number | null
          upi_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "v_owner_summary"
            referencedColumns: ["owner_id"]
          },
        ]
      }
      v_house_month_summary: {
        Row: {
          bill_count: number | null
          bill_month: string | null
          house_id: string | null
          owner_id: string | null
          total_billed: number | null
          total_collected: number | null
          total_electricity: number | null
          total_extra_charges: number | null
          total_pending: number | null
          total_rent: number | null
          total_units: number | null
        }
        Relationships: [
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "houses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "v_owner_summary"
            referencedColumns: ["owner_id"]
          },
        ]
      }
      v_owner_summary: {
        Row: {
          owner_id: string | null
          pending: number | null
          properties: number | null
          tenants: number | null
        }
        Insert: {
          owner_id?: string | null
          pending?: never
          properties?: never
          tenants?: never
        }
        Update: {
          owner_id?: string | null
          pending?: never
          properties?: never
          tenants?: never
        }
        Relationships: []
      }
      v_tenant_list: {
        Row: {
          agreement_expiry: string | null
          electricity_rate: number | null
          floor_number: number | null
          house_id: string | null
          house_name: string | null
          id: string | null
          is_active: boolean | null
          last_bill_month: string | null
          mobile_number: string | null
          monthly_rent: number | null
          name: string | null
          owner_id: string | null
          total_pending: number | null
        }
        Relationships: [
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_list"
            referencedColumns: ["id", "owner_id"]
          },
          {
            foreignKeyName: "tenants_house_fk"
            columns: ["house_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "v_house_month_summary"
            referencedColumns: ["house_id", "owner_id"]
          },
        ]
      }
    }
    Functions: {
      bill_draft: {
        Args: { p_month: string; p_tenant: string }
        Returns: {
          amount_paid: number
          bill_id: string
          charges: Json
          current_reading: number
          electricity_rate: number
          previous_balance: number
          previous_reading: number
          rent_amount: number
        }[]
      }
      carry_forward_balance: {
        Args: { p_month: string; p_tenant: string }
        Returns: number
      }
      ensure_profile: {
        Args: never
        Returns: {
          created_at: string
          currency: string
          default_gpay_number: string | null
          default_upi_id: string | null
          id: string
          mobile_number: string | null
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "users"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      next_previous_reading: {
        Args: { p_month: string; p_tenant: string }
        Returns: number
      }
      save_bill: {
        Args: {
          p_amount_paid: number
          p_charges?: Json
          p_current_reading: number
          p_month: string
          p_tenant: string
        }
        Returns: string
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
