// Regenerates src/types/database.ts from the live schema.
//
//   npm run gen-types
//
// Run it after every migration. The generated file is committed so that
// `tsc` works without database access, which means it silently goes stale if
// you skip this step.
//
// Why a script instead of a one-line npm script: the connection string
// contains `&`, which breaks argument splitting once cmd.exe is involved, and
// npm scripts do not load .env.local. Both bite on Windows specifically.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const ENV_FILE = ".env.local";
const OUT = "src/types/database.ts";
const KEY = "DATABASE_URL_UNPOOLED";

if (!existsSync(ENV_FILE)) {
  console.error(`Missing ${ENV_FILE}.`);
  process.exit(1);
}

let dbUrl;
for (const line of readFileSync(ENV_FILE, "utf8").split(/\r?\n/)) {
  if (line.trimStart().startsWith("#")) continue;
  const i = line.indexOf("=");
  if (i > 0 && line.slice(0, i).trim() === KEY) {
    dbUrl = line.slice(i + 1).trim().replace(/^["']|["']$/g, "");
  }
}
if (!dbUrl) {
  console.error(`${KEY} not found in ${ENV_FILE}. Copy the direct (non-pooled) connection string from the Neon console.`);
  process.exit(1);
}

// Introspection needs a direct connection; the pooler cannot serve it.
if (dbUrl.includes("-pooler.")) {
  console.error(`${KEY} points at the pooler. Strip "-pooler" from the host.`);
  process.exit(1);
}

const res = spawnSync(
  `npx -y @neondatabase/neon-js gen-types --db-url "${dbUrl}" --output "${OUT}" -s public`,
  { encoding: "utf8", shell: true },
);

// Never let the connection string reach the terminal or a CI log.
const scrub = (s) => (s ?? "").replaceAll(dbUrl, "<redacted>");
if (res.status !== 0) {
  console.error(scrub(res.stdout));
  console.error(scrub(res.stderr));
  process.exit(res.status ?? 1);
}

// The generator overwrites the file wholesale, so the banner is re-applied here
// rather than kept in the file itself.
const banner = `// Generated by \`npm run gen-types\` (@neondatabase/neon-js gen-types).
// DO NOT EDIT BY HAND — regenerate after every migration in src/db/migrations.
//
// Covers tables, views and functions in the public schema. Passed to
// NeonPostgrestClient<Database> in src/lib/data-api.ts, which is what makes
// every .from()/.rpc() call in the app type-checked.

`;
writeFileSync(OUT, banner + readFileSync(OUT, "utf8"));

console.log(`Types written to ${OUT}`);
